# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlgastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlgastos.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='cuenta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controlgastos.Cuenta'),
        ),
    ]
