# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlgastos', '0002_auto_20171123_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('monto', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controlgastos.Categoria')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controlgastos.Usuario')),
            ],
        ),
    ]
