# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlgastos', '0003_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
