language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=1.11
  
before_install:
  - export PYTHONPATH=$HOME/builds/marianovecco/Trabajo-Final/tpfinal

install:
  - pip install -q Django==$DJANGO_VERSION

script:
  - python manage.py test
