language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=1.11
  
before_install:
  - export PYTHONPATH=$HOME/builds/marianovecco/Trabajo-Final/

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install djangorestframework
  - pip install coveralls

script:
  - cd tpfinal
  - python manage.py test controlgastos
  - coverage run --source=controlgastos manage.py test controlgastos

after_success:
  - coveralls
